name: Build Android (Godot 4)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  export-android:
    runs-on: ubuntu-latest
    env:
      GODOT_VERSION: "4.2.2"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Godot from GitHub mirror
        run: |
          # Скачиваем бинарник и экспортные шаблоны (tpz = zip)
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz

          # Распаковка Godot
          unzip -o Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip -d godot
          chmod +x godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64

          # Распаковка экспортных шаблонов
          TEMPL=~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          mkdir -p "$TEMPL"
          unzip -o Godot_v${GODOT_VERSION}-stable_export_templates.tpz -d "$TEMPL"

          # В tpz всё внутри папки "templates/" — поднимем файлы на уровень выше
          if [ -d "$TEMPL/templates" ]; then
            mv "$TEMPL/templates/"* "$TEMPL"/
            rmdir "$TEMPL/templates"
          fi

          echo "== Templates listing =="
          ls -la "$TEMPL"
          ls -la "$TEMPL/android" || true

      - name: Unpack project zip if present
        run: |
          if [ -f ParkourBhop_Godot4_Project.zip ]; then
            echo "Found project zip, unpacking..."
            unzip -o ParkourBhop_Godot4_Project.zip -d .
          else
            echo "No project zip found, assuming files are already unpacked."
          fi
          echo "== Repo root after unpack =="
          ls -la

      - name: Quick sanity check (project files)
        run: |
          echo "project.godot present?"; test -f project.godot && echo YES || (echo NO && exit 1)
          echo "export_presets.cfg present?"; test -f export_presets.cfg && echo YES || (echo NO && exit 1)

      - name: Export Android APK (Debug)
        run: |
          ./godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64 --headless --path . --export-debug "Android" build/ParkourBhop-debug.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ParkourBhop-debug.apk
          path: build/ParkourBhop-debug.apk

      - name: Create Release (if tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/ParkourBhop-debug.apk
