name: Build Android (Godot 4)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  export-android:
    runs-on: ubuntu-latest
    env:
      GODOT_VERSION: "4.2.2"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Godot from GitHub mirror
        run: |
          # Бинарник и экспортные шаблоны (tpz = zip)
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz

          # Распаковать бинарник
          unzip -o Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip -d godot
          chmod +x godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64

          # Распаковать экспортные шаблоны
          TEMPL=~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          mkdir -p "$TEMPL"
          unzip -o Godot_v${GODOT_VERSION}-stable_export_templates.tpz -d "$TEMPL"

          # Внутри tpz всё в подпапке "templates/" — поднимем наверх
          if [ -d "$TEMPL/templates" ]; then
            mv "$TEMPL/templates/"* "$TEMPL"/
            rmdir "$TEMPL/templates"
          fi

      - name: Unpack project zip if present
        run: |
          if [ -f ParkourBhop_Godot4_Project.zip ]; then
            unzip -o ParkourBhop_Godot4_Project.zip -d .
          fi
          ls -la

      - name: Quick sanity check (project files)
        run: |
          test -f project.godot || (echo "project.godot missing" && exit 1)
          test -f export_presets.cfg || (echo "export_presets.cfg missing" && exit 1)

      - name: Create debug keystore
        run: |
          mkdir -p ~/.android
          keytool -genkeypair -alias androiddebugkey \
            -keypass android -keystore ~/.android/debug.keystore \
            -storepass android -dname "CN=Android Debug,O=Android,C=US" \
            -keyalg RSA -keysize 2048 -validity 10000

      - name: Configure Godot Editor Settings for Android export
        run: |
          mkdir -p ~/.config/godot
          cat > ~/.config/godot/editor_settings-4.tres << 'EOF'
          [gd_resource type="EditorSettings" load_steps=2 format=3]

          [resource]
          export/android/debug_keystore = "~/.android/debug.keystore"
          export/android/debug_keystore_user = "androiddebugkey"
          export/android/debug_keystore_pass = "android"
          EOF
          echo "== Editor settings written =="
          cat ~/.config/godot/editor_settings-4.tres || true

      - name: Export Android APK (Debug)
        run: |
          ./godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64 \
            --headless --path . --export-debug "Android" build/ParkourBhop-debug.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ParkourBhop-debug.apk
          path: build/ParkourBhop-debug.apk

      - name: Create Release (if tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/ParkourBhop-debug.apk
