name: Build Android (Godot 4)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  export-android:
    runs-on: ubuntu-latest
    env:
      GODOT_VERSION: "4.2.2"
      RUNNER_HOME: "/home/runner"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Godot from GitHub mirror
        run: |
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
          unzip -o Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip -d godot
          chmod +x godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64
          TEMPL=${RUNNER_HOME}/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          mkdir -p "$TEMPL"
          unzip -o Godot_v${GODOT_VERSION}-stable_export_templates.tpz -d "$TEMPL"
          if [ -d "$TEMPL/templates" ]; then mv "$TEMPL/templates/"* "$TEMPL"/ && rmdir "$TEMPL/templates"; fi

      - name: Unpack project zip if present
        run: |
          if [ -f ParkourBhop_Godot4_Project.zip ]; then unzip -o ParkourBhop_Godot4_Project.zip -d .; fi
          ls -la

      - name: Ensure project files exist
        run: |
          test -f project.godot || (echo "project.godot missing" && exit 1)

      - name: Create debug keystore
        run: |
          mkdir -p ${RUNNER_HOME}/.android
          keytool -genkeypair -alias androiddebugkey \
            -keypass android -keystore ${RUNNER_HOME}/.android/debug.keystore \
            -storepass android -dname "CN=Android Debug,O=Android,C=US" \
            -keyalg RSA -keysize 2048 -validity 10000

      - name: Configure Editor Settings (debug keystore)
        run: |
          mkdir -p ${RUNNER_HOME}/.config/godot
          cat > ${RUNNER_HOME}/.config/godot/editor_settings-4.tres << EOF
          [gd_resource type="EditorSettings" load_steps=2 format=3]

          [resource]
          export/android/debug_keystore = "${RUNNER_HOME}/.android/debug.keystore"
          export/android/debug_keystore_user = "androiddebugkey"
          export/android/debug_keystore_pass = "android"
          EOF
          cat ${RUNNER_HOME}/.config/godot/editor_settings-4.tres || true

      - name: Write export_presets.cfg (set BOTH debug & release to debug keystore)
        run: |
          cat > export_presets.cfg << EOF
          [preset.0]
          name="Android"
          platform="Android"
          runnable=true
          custom_features=""
          export_filter="all_resources"
          include_filter=""
          exclude_filter=""
          export_path="build/ParkourBhop-debug.apk"
          encryption_include_filters=""
          encryption_exclude_filters=""
          encrypt_pck=false
          encrypt_directory=false

          [preset.0.options]
          custom_template/debug=""
          custom_template/release=""
          architectures/armeabi-v7a=true
          architectures/arm64-v8a=true
          architectures/x86=false
          architectures/x86_64=false
          one_click_deploy/clear_previous_install=true
          version/code=1
          version/name="0.1.0"
          package/unique_name="org.example.parkourbhop"
          package/name="ParkourBhop"
          launcher_icons/main_192x192="res://icon.png"
          graphics/32_bits_framebuffer=true
          screen/immersive_mode=true
          xr_features/xr_mode=0
          # <- ВАЖНО: и debug, и release указывают на один debug keystore
          keystore/debug="${RUNNER_HOME}/.android/debug.keystore"
          keystore/debug_user="androiddebugkey"
          keystore/debug_password="android"
          keystore/release="${RUNNER_HOME}/.android/debug.keystore"
          keystore/release_user="androiddebugkey"
          keystore/release_password="android"
          EOF

          echo "== export_presets.cfg =="
          cat export_presets.cfg

      - name: Export Android APK (Debug)
        run: |
          ./godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64 \
            --headless --path . --export-debug "Android" build/ParkourBhop-debug.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ParkourBhop-debug.apk
          path: build/ParkourBhop-debug.apk
