name: Build Android (Godot 4)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  export-android:
    runs-on: ubuntu-latest
    env:
      GODOT_VERSION: "4.2.2"
      HOME: "/home/runner"
      XDG_CONFIG_HOME: "/home/runner/.config"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Godot from GitHub mirror
        run: |
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip
          wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
          unzip -o Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip -d godot
          chmod +x godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64
          TEMPL=${HOME}/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          mkdir -p "$TEMPL"
          unzip -o Godot_v${GODOT_VERSION}-stable_export_templates.tpz -d "$TEMPL"
          if [ -d "$TEMPL/templates" ]; then mv "$TEMPL/templates/"* "$TEMPL"/ && rmdir "$TEMPL/templates"; fi

      - name: Unpack project zip if present
        run: |
          if [ -f ParkourBhop_Godot4_Project.zip ]; then unzip -o ParkourBhop_Godot4_Project.zip -d .; fi
          ls -la

      - name: Ensure project files exist
        run: |
          test -f project.godot || (echo "project.godot missing" && exit 1)
          test -f export_presets.cfg || (echo "export_presets.cfg missing" && exit 1)

      - name: Create debug keystore
        run: |
          mkdir -p ${HOME}/.android
          keytool -genkeypair -alias androiddebugkey \
            -keypass android -keystore ${HOME}/.android/debug.keystore \
            -storepass android -dname "CN=Android Debug,O=Android,C=US" \
            -keyalg RSA -keysize 2048 -validity 10000
          keytool -list -keystore ${HOME}/.android/debug.keystore -storepass android

      - name: Configure Editor Settings (debug keystore)
        run: |
          mkdir -p ${XDG_CONFIG_HOME}/godot
          cat > ${XDG_CONFIG_HOME}/godot/editor_settings-4.tres << EOF
          [gd_resource type="EditorSettings" load_steps=2 format=3]

          [resource]
          export/android/debug_keystore = "${HOME}/.android/debug.keystore"
          export/android/debug_keystore_user = "androiddebugkey"
          export/android/debug_keystore_pass = "android"
          EOF
          cat ${XDG_CONFIG_HOME}/godot/editor_settings-4.tres || true

      - name: Export Android APK (Debug)
        run: |
          ./godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64 \
            --headless --path . --export-debug "Android" build/ParkourBhop-debug.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ParkourBhop-debug.apk
          path: build/ParkourBhop-debug.apk
